ample::enum_labeled!(
    #[derive(Debug)]
    pub enum Data,
    u16,
    "Data endianness",
    [
        [0   ; EmNone          ; EM_NONE             ; "EM_NONE"            ; "No machine"],
        [1   ; EmM32           ; EM_M32              ; "EM_M32"             ; "AT&T WE 32100"],
        [2   ; EmSparc         ; EM_SPARC            ; "EM_SPARC"           ; "SPARC"],
        [3   ; Em386           ; EM_386              ; "EM_386"             ; "Intel 80386"],
        [4   ; Em68K           ; EM_68K              ; "EM_68K"             ; "Motorola 68000"],
        [5   ; Em88K           ; EM_88K              ; "EM_88K"             ; "Motorola 88000"],
        [6   ; EmIamcu         ; EM_IAMCU            ; "EM_IAMCU"           ; "Intel MCU"],
        [7   ; Em860           ; EM_860              ; "EM_860"             ; "Intel 80860"],
        [8   ; EmMips          ; EM_MIPS             ; "EM_MIPS"            ; "MIPS I Architecture"],
        [9   ; EmS370          ; EM_S370             ; "EM_S370"            ; "IBM System/370 Processor"],
        [10  ; EmMipsRs3Le     ; EM_MIPS_RS3_LE      ; "EM_MIPS_RS3_LE"     ; "MIPS RS3000 Little-endian"],
        // reserved 11–14 Reserved for future use
        [15  ; EmParisc        ; EM_PARISC           ; "EM_PARISC"          ; "Hewlett-Packard PA-RISC"],
        // reserved 16 Reserved for future use
        [17  ; EmVpp500        ; EM_VPP500           ; "EM_VPP500"          ; "Fujitsu VPP500"],
        [18  ; EmSparc32Plus   ; EM_SPARC32PLUS      ; "EM_SPARC32PLUS"     ; "Enhanced instruction set SPARC"],
        [19  ; Em960           ; EM_960              ; "EM_960"             ; "Intel 80960"],
        [20  ; EmPpc           ; EM_PPC              ; "EM_PPC"             ; "PowerPC"],
        [21  ; EmPpc64         ; EM_PPC64            ; "EM_PPC64"           ; "64-bit PowerPC"],
        [22  ; EmS390          ; EM_S390             ; "EM_S390"            ; "IBM System/390 Processor"],
        [23  ; EmSpu           ; EM_SPU              ; "EM_SPU"             ; "IBM SPU/SPC"],
        // reserved 24–35 Reserved for future use
        [36  ; EmV800          ; EM_V800             ; "EM_V800"            ; "NEC V800"],
        [37  ; EmFr20          ; EM_FR20             ; "EM_FR20"            ; "Fujitsu FR20"],
        [38  ; EmRh32          ; EM_RH32             ; "EM_RH32"            ; "TRW RH-32"],
        [39  ; EmRce           ; EM_RCE              ; "EM_RCE"             ; "Motorola RCE"],
        [40  ; EmArm           ; EM_ARM              ; "EM_ARM"             ; "ARM 32-bit architecture (AARCH32)"],
        [41  ; EmAlpha         ; EM_ALPHA            ; "EM_ALPHA"           ; "Digital Alpha"],
        [42  ; EmSh            ; EM_SH               ; "EM_SH"              ; "Hitachi SH"],
        [43  ; EmSparcv9       ; EM_SPARCV9          ; "EM_SPARCV9"         ; "SPARC Version 9"],
        [44  ; EmTricore       ; EM_TRICORE          ; "EM_TRICORE"         ; "Siemens TriCore embedded processor"],
        [45  ; EmArc           ; EM_ARC              ; "EM_ARC"             ; "Argonaut RISC Core, Argonaut Technologies Inc."],
        [46  ; EmH8300         ; EM_H8_300           ; "EM_H8_300"          ; "Hitachi H8/300"],
        [47  ; EmH8300H        ; EM_H8_300H          ; "EM_H8_300H"         ; "Hitachi H8/300H"],
        [48  ; EmH8S           ; EM_H8S              ; "EM_H8S"             ; "Hitachi H8S"],
        [49  ; EmH8500         ; EM_H8_500           ; "EM_H8_500"          ; "Hitachi H8/500"],
        [50  ; EmIa64          ; EM_IA_64            ; "EM_IA_64"           ; "Intel IA-64 processor architecture"],
        [51  ; EmMipsX         ; EM_MIPS_X           ; "EM_MIPS_X"          ; "Stanford MIPS-X"],
        [52  ; EmColdfire      ; EM_COLDFIRE         ; "EM_COLDFIRE"        ; "Motorola ColdFire"],
        [53  ; Em68Hc12        ; EM_68HC12           ; "EM_68HC12"          ; "Motorola M68HC12"],
        [54  ; EmMma           ; EM_MMA              ; "EM_MMA"             ; "Fujitsu MMA Multimedia Accelerator"],
        [55  ; EmPcp           ; EM_PCP              ; "EM_PCP"             ; "Siemens PCP"],
        [56  ; EmNcpu          ; EM_NCPU             ; "EM_NCPU"            ; "Sony nCPU embedded RISC processor"],
        [57  ; EmNdr1          ; EM_NDR1             ; "EM_NDR1"            ; "Denso NDR1 microprocessor"],
        [58  ; EmStarcore      ; EM_STARCORE         ; "EM_STARCORE"        ; "Motorola Star*Core processor"],
        [59  ; EmMe16          ; EM_ME16             ; "EM_ME16"            ; "Toyota ME16 processor"],
        [60  ; EmSt100         ; EM_ST100            ; "EM_ST100"           ; "STMicroelectronics ST100 processor"],
        [61  ; EmTinyj         ; EM_TINYJ            ; "EM_TINYJ"           ; "Advanced Logic Corp. TinyJ embedded processor family"],
        [62  ; EmX8664         ; EM_X86_64           ; "EM_X86_64"          ; "AMD x86-64 architecture"],
        [63  ; EmPdsp          ; EM_PDSP             ; "EM_PDSP"            ; "Sony DSP Processor"],
        [64  ; EmPdp10         ; EM_PDP10            ; "EM_PDP10"           ; "Digital Equipment Corp. PDP-10"],
        [65  ; EmPdp11         ; EM_PDP11            ; "EM_PDP11"           ; "Digital Equipment Corp. PDP-11"],
        [66  ; EmFx66          ; EM_FX66             ; "EM_FX66"            ; "Siemens FX66 microcontroller"],
        [67  ; EmSt9Plus       ; EM_ST9PLUS          ; "EM_ST9PLUS"         ; "STMicroelectronics ST9+ 8/16 bit microcontroller"],
        [68  ; EmSt7           ; EM_ST7              ; "EM_ST7"             ; "STMicroelectronics ST7 8-bit microcontroller"],
        [69  ; Em68Hc16        ; EM_68HC16           ; "EM_68HC16"          ; "Motorola MC68HC16 Microcontroller"],
        [70  ; Em68Hc11        ; EM_68HC11           ; "EM_68HC11"          ; "Motorola MC68HC11 Microcontroller"],
        [71  ; Em68Hc08        ; EM_68HC08           ; "EM_68HC08"          ; "Motorola MC68HC08 Microcontroller"],
        [72  ; Em68Hc05        ; EM_68HC05           ; "EM_68HC05"          ; "Motorola MC68HC05 Microcontroller"],
        [73  ; EmSvx           ; EM_SVX              ; "EM_SVX"             ; "Silicon Graphics SVx"],
        [74  ; EmSt19          ; EM_ST19             ; "EM_ST19"            ; "STMicroelectronics ST19 8-bit microcontroller"],
        [75  ; EmVax           ; EM_VAX              ; "EM_VAX"             ; "Digital VAX"],
        [76  ; EmCris          ; EM_CRIS             ; "EM_CRIS"            ; "Axis Communications 32-bit embedded processor"],
        [77  ; EmJavelin       ; EM_JAVELIN          ; "EM_JAVELIN"         ; "Infineon Technologies 32-bit embedded processor"],
        [78  ; EmFirepath      ; EM_FIREPATH         ; "EM_FIREPATH"        ; "Element 14 64-bit DSP Processor"],
        [79  ; EmZsp           ; EM_ZSP              ; "EM_ZSP"             ; "LSI Logic 16-bit DSP Processor"],
        [80  ; EmMmix          ; EM_MMIX             ; "EM_MMIX"            ; "Donald Knuth’s educational 64-bit processor"],
        [81  ; EmHuany         ; EM_HUANY            ; "EM_HUANY"           ; "Harvard University machine-independent object files"],
        [82  ; EmPrism         ; EM_PRISM            ; "EM_PRISM"           ; "SiTera Prism"],
        [83  ; EmAvr           ; EM_AVR              ; "EM_AVR"             ; "Atmel AVR 8-bit microcontroller"],
        [84  ; EmFr30          ; EM_FR30             ; "EM_FR30"            ; "Fujitsu FR30"],
        [85  ; EmD10V          ; EM_D10V             ; "EM_D10V"            ; "Mitsubishi D10V"],
        [86  ; EmD30V          ; EM_D30V             ; "EM_D30V"            ; "Mitsubishi D30V"],
        [87  ; EmV850          ; EM_V850             ; "EM_V850"            ; "NEC v850"],
        [88  ; EmM32R          ; EM_M32R             ; "EM_M32R"            ; "Mitsubishi M32R"],
        [89  ; EmMn10300       ; EM_MN10300          ; "EM_MN10300"         ; "Matsushita MN10300"],
        [90  ; EmMn10200       ; EM_MN10200          ; "EM_MN10200"         ; "Matsushita MN10200"],
        [91  ; EmPj            ; EM_PJ               ; "EM_PJ"              ; "picoJava"],
        [92  ; EmOpenrisc      ; EM_OPENRISC         ; "EM_OPENRISC"        ; "OpenRISC 32-bit embedded processor"],
        [93  ; EmArcCompact    ; EM_ARC_COMPACT      ; "EM_ARC_COMPACT"     ; "ARC International ARCompact processor (old spelling/synonym: EM_ARC_A5)"],
        [94  ; EmXtensa        ; EM_XTENSA           ; "EM_XTENSA"          ; "Tensilica Xtensa Architecture"],
        [95  ; EmVideocore     ; EM_VIDEOCORE        ; "EM_VIDEOCORE"       ; "Alphamosaic VideoCore processor"],
        [96  ; EmTmmGpp        ; EM_TMM_GPP          ; "EM_TMM_GPP"         ; "Thompson Multimedia General Purpose Processor"],
        [97  ; EmNs32K         ; EM_NS32K            ; "EM_NS32K"           ; "National Semiconductor 32000 series"],
        [98  ; EmTpc           ; EM_TPC              ; "EM_TPC"             ; "Tenor Network TPC processor"],
        [99  ; EmSnp1K         ; EM_SNP1K            ; "EM_SNP1K"           ; "Trebia SNP 1000 processor"],
        [100 ; EmSt200         ; EM_ST200            ; "EM_ST200"           ; "STMicroelectronics (www.st.com) ST200 microcontroller"],
        [101 ; EmIp2K          ; EM_IP2K             ; "EM_IP2K"            ; "Ubicom IP2xxx microcontroller family"],
        [102 ; EmMax           ; EM_MAX              ; "EM_MAX"             ; "MAX Processor"],
        [103 ; EmCr            ; EM_CR               ; "EM_CR"              ; "National Semiconductor CompactRISC microprocessor"],
        [104 ; EmF2Mc16        ; EM_F2MC16           ; "EM_F2MC16"          ; "Fujitsu F2MC16"],
        [105 ; EmMsp430        ; EM_MSP430           ; "EM_MSP430"          ; "Texas Instruments embedded microcontroller msp430"],
        [106 ; EmBlackfin      ; EM_BLACKFIN         ; "EM_BLACKFIN"        ; "Analog Devices Blackfin (DSP) processor"],
        [107 ; EmSeC33         ; EM_SE_C33           ; "EM_SE_C33"          ; "S1C33 Family of Seiko Epson processors"],
        [108 ; EmSep           ; EM_SEP              ; "EM_SEP"             ; "Sharp embedded microprocessor"],
        [109 ; EmArca          ; EM_ARCA             ; "EM_ARCA"            ; "Arca RISC Microprocessor"],
        [110 ; EmUnicore       ; EM_UNICORE          ; "EM_UNICORE"         ; "Microprocessor series from PKU-Unity Ltd. and MPRC of Peking University"],
        [111 ; EmExcess        ; EM_EXCESS           ; "EM_EXCESS"          ; "eXcess: 16/32/64-bit configurable embedded CPU"],
        [112 ; EmDxp           ; EM_DXP              ; "EM_DXP"             ; "Icera Semiconductor Inc. Deep Execution Processor"],
        [113 ; EmAlteraNios2   ; EM_ALTERA_NIOS2     ; "EM_ALTERA_NIOS2"    ; "Altera Nios II soft-core processor"],
        [114 ; EmCrx           ; EM_CRX              ; "EM_CRX"             ; "National Semiconductor CompactRISC CRX microprocessor"],
        [115 ; EmXgate         ; EM_XGATE            ; "EM_XGATE"           ; "Motorola XGATE embedded processor"],
        [116 ; EmC166          ; EM_C166             ; "EM_C166"            ; "Infineon C16x/XC16x processor"],
        [117 ; EmM16C          ; EM_M16C             ; "EM_M16C"            ; "Renesas M16C series microprocessors"],
        [118 ; EmDspic30F      ; EM_DSPIC30F         ; "EM_DSPIC30F"        ; "Microchip Technology dsPIC30F Digital Signal Controller"],
        [119 ; EmCe            ; EM_CE               ; "EM_CE"              ; "Freescale Communication Engine RISC core"],
        [120 ; EmM32C          ; EM_M32C             ; "EM_M32C"            ; "Renesas M32C series microprocessors"],
        // reserved 121–130 Reserved for future use
        [131 ; EmTsk3000       ; EM_TSK3000          ; "EM_TSK3000"         ; "Altium TSK3000 core"],
        [132 ; EmRs08          ; EM_RS08             ; "EM_RS08"            ; "Freescale RS08 embedded processor"],
        [133 ; EmSharc         ; EM_SHARC            ; "EM_SHARC"           ; "Analog Devices SHARC family of 32-bit DSP processors"],
        [134 ; EmEcog2         ; EM_ECOG2            ; "EM_ECOG2"           ; "Cyan Technology eCOG2 microprocessor"],
        [135 ; EmScore7        ; EM_SCORE7           ; "EM_SCORE7"          ; "Sunplus S+core7 RISC processor"],
        [136 ; EmDsp24         ; EM_DSP24            ; "EM_DSP24"           ; "New Japan Radio (NJR) 24-bit DSP Processor"],
        [137 ; EmVideocore3    ; EM_VIDEOCORE3       ; "EM_VIDEOCORE3"      ; "Broadcom VideoCore III processor"],
        [138 ; EmLatticemico32 ; EM_LATTICEMICO32    ; "EM_LATTICEMICO32"   ; "RISC processor for Lattice FPGA architecture"],
        [139 ; EmSeC17         ; EM_SE_C17           ; "EM_SE_C17"          ; "Seiko Epson C17 family"],
        [140 ; EmTiC6000       ; EM_TI_C6000         ; "EM_TI_C6000"        ; "The Texas Instruments TMS320C6000 DSP family"],
        [141 ; EmTiC2000       ; EM_TI_C2000         ; "EM_TI_C2000"        ; "The Texas Instruments TMS320C2000 DSP family"],
        [142 ; EmTiC5500       ; EM_TI_C5500         ; "EM_TI_C5500"        ; "The Texas Instruments TMS320C55x DSP family"],
        [143 ; EmTiArp32       ; EM_TI_ARP32         ; "EM_TI_ARP32"        ; "Texas Instruments Application Specific RISC Processor, 32bit fetch"],
        [144 ; EmTiPru         ; EM_TI_PRU           ; "EM_TI_PRU"          ; "Texas Instruments Programmable Realtime Unit"],
        // reserved 145–159 Reserved for future use
        [160 ; EmMmdspPlus     ; EM_MMDSP_PLUS       ; "EM_MMDSP_PLUS"      ; "STMicroelectronics 64bit VLIW Data Signal Processor"],
        [161 ; EmCypressM8C    ; EM_CYPRESS_M8C      ; "EM_CYPRESS_M8C"     ; "Cypress M8C microprocessor"],
        [162 ; EmR32C          ; EM_R32C             ; "EM_R32C"            ; "Renesas R32C series microprocessors"],
        [163 ; EmTrimedia      ; EM_TRIMEDIA         ; "EM_TRIMEDIA"        ; "NXP Semiconductors TriMedia architecture family"],
        [164 ; EmQdsp6         ; EM_QDSP6            ; "EM_QDSP6"           ; "QUALCOMM DSP6 Processor"],
        [165 ; Em8051          ; EM_8051             ; "EM_8051"            ; "Intel 8051 and variants"],
        [166 ; EmStxp7X        ; EM_STXP7X           ; "EM_STXP7X"          ; "STMicroelectronics STxP7x family of configurable and extensible RISC processors"],
        [167 ; EmNds32         ; EM_NDS32            ; "EM_NDS32"           ; "Andes Technology compact code size embedded RISC processor family"],
        [168 ; EmEcog1         ; EM_ECOG1, EM_ECOG1X ; "EM_ECOG1"           ; "Cyan Technology eCOG1X family"],
        // [168                                       ; EmEcog1X        ; EM_ECOG1X           ; "EM_ECOG1X"          ; "Cyan Technology eCOG1X family"],
        [169 ; EmMaxq30        ; EM_MAXQ30           ; "EM_MAXQ30"          ; "Dallas Semiconductor MAXQ30 Core Micro-controllers"],
        [170 ; EmXimo16        ; EM_XIMO16           ; "EM_XIMO16"          ; "New Japan Radio (NJR) 16-bit DSP Processor"],
        [171 ; EmManik         ; EM_MANIK            ; "EM_MANIK"           ; "M2000 Reconfigurable RISC Microprocessor"],
        [172 ; EmCraynv2       ; EM_CRAYNV2          ; "EM_CRAYNV2"         ; "Cray Inc. NV2 vector architecture"],
        [173 ; EmRx            ; EM_RX               ; "EM_RX"              ; "Renesas RX family"],
        [174 ; EmMetag         ; EM_METAG            ; "EM_METAG"           ; "Imagination Technologies META processor architecture"],
        [175 ; EmMcstElbrus    ; EM_MCST_ELBRUS      ; "EM_MCST_ELBRUS"     ; "MCST Elbrus general purpose hardware architecture"],
        [176 ; EmEcog16        ; EM_ECOG16           ; "EM_ECOG16"          ; "Cyan Technology eCOG16 family"],
        [177 ; EmCr16          ; EM_CR16             ; "EM_CR16"            ; "National Semiconductor CompactRISC CR16 16-bit microprocessor"],
        [178 ; EmEtpu          ; EM_ETPU             ; "EM_ETPU"            ; "Freescale Extended Time Processing Unit"],
        [179 ; EmSle9X         ; EM_SLE9X            ; "EM_SLE9X"           ; "Infineon Technologies SLE9X core"],
        [180 ; EmL10M          ; EM_L10M             ; "EM_L10M"            ; "Intel L10M"],
        [181 ; EmK10M          ; EM_K10M             ; "EM_K10M"            ; "Intel K10M"],
        // reserved 182 Reserved for future Intel use
        [183 ; EmAarch64       ; EM_AARCH64          ; "EM_AARCH64"         ; "ARM 64-bit architecture (AARCH64)"],
        // reserved 184 Reserved for future ARM use
        [185 ; EmAvr32         ; EM_AVR32            ; "EM_AVR32"           ; "Atmel Corporation 32-bit microprocessor family"],
        [186 ; EmStm8          ; EM_STM8             ; "EM_STM8"            ; "STMicroeletronics STM8 8-bit microcontroller"],
        [187 ; EmTile64        ; EM_TILE64           ; "EM_TILE64"          ; "Tilera TILE64 multicore architecture family"],
        [188 ; EmTilepro       ; EM_TILEPRO          ; "EM_TILEPRO"         ; "Tilera TILEPro multicore architecture family"],
        [189 ; EmMicroblaze    ; EM_MICROBLAZE       ; "EM_MICROBLAZE"      ; "Xilinx MicroBlaze 32-bit RISC soft processor core"],
        [190 ; EmCuda          ; EM_CUDA             ; "EM_CUDA"            ; "NVIDIA CUDA architecture"],
        [191 ; EmTilegx        ; EM_TILEGX           ; "EM_TILEGX"          ; "Tilera TILE-Gx multicore architecture family"],
        [192 ; EmCloudshield   ; EM_CLOUDSHIELD      ; "EM_CLOUDSHIELD"     ; "CloudShield architecture family"],
        [193 ; EmCorea1St      ; EM_COREA_1ST        ; "EM_COREA_1ST"       ; "KIPO-KAIST Core-A 1st generation processor family"],
        [194 ; EmCorea2Nd      ; EM_COREA_2ND        ; "EM_COREA_2ND"       ; "KIPO-KAIST Core-A 2nd generation processor family"],
        [195 ; EmArcCompact2   ; EM_ARC_COMPACT2     ; "EM_ARC_COMPACT2"    ; "Synopsys ARCompact V2"],
        [196 ; EmOpen8         ; EM_OPEN8            ; "EM_OPEN8"           ; "Open8 8-bit RISC soft processor core"],
        [197 ; EmRl78          ; EM_RL78             ; "EM_RL78"            ; "Renesas RL78 family"],
        [198 ; EmVideocore5    ; EM_VIDEOCORE5       ; "EM_VIDEOCORE5"      ; "Broadcom VideoCore V processor"],
        [199 ; Em78Kor         ; EM_78KOR            ; "EM_78KOR"           ; "Renesas 78KOR family"],
        [200 ; Em56800Ex       ; EM_56800EX          ; "EM_56800EX"         ; "Freescale 56800EX Digital Signal Controller (DSC)"],
        [201 ; EmBa1           ; EM_BA1              ; "EM_BA1"             ; "Beyond BA1 CPU architecture"],
        [202 ; EmBa2           ; EM_BA2              ; "EM_BA2"             ; "Beyond BA2 CPU architecture"],
        [203 ; EmXcore         ; EM_XCORE            ; "EM_XCORE"           ; "XMOS xCORE processor family"],
        [204 ; EmMchpPic       ; EM_MCHP_PIC         ; "EM_MCHP_PIC"        ; "Microchip 8-bit PIC(r) family"],
        [205 ; EmIntel205      ; EM_INTEL205         ; "EM_INTEL205"        ; "Reserved by Intel"],
        [206 ; EmIntel206      ; EM_INTEL206         ; "EM_INTEL206"        ; "Reserved by Intel"],
        [207 ; EmIntel207      ; EM_INTEL207         ; "EM_INTEL207"        ; "Reserved by Intel"],
        [208 ; EmIntel208      ; EM_INTEL208         ; "EM_INTEL208"        ; "Reserved by Intel"],
        [209 ; EmIntel209      ; EM_INTEL209         ; "EM_INTEL209"        ; "Reserved by Intel"],
        [210 ; EmKm32          ; EM_KM32             ; "EM_KM32"            ; "KM211 KM32 32-bit processor"],
        [211 ; EmKmx32         ; EM_KMX32            ; "EM_KMX32"           ; "KM211 KMX32 32-bit processor"],
        [212 ; EmKmx16         ; EM_KMX16            ; "EM_KMX16"           ; "KM211 KMX16 16-bit processor"],
        [213 ; EmKmx8          ; EM_KMX8             ; "EM_KMX8"            ; "KM211 KMX8 8-bit processor"],
        [214 ; EmKvarc         ; EM_KVARC            ; "EM_KVARC"           ; "KM211 KVARC processor"],
        [215 ; EmCdp           ; EM_CDP              ; "EM_CDP"             ; "Paneve CDP architecture family"],
        [216 ; EmCoge          ; EM_COGE             ; "EM_COGE"            ; "Cognitive Smart Memory Processor"],
        [217 ; EmCool          ; EM_COOL             ; "EM_COOL"            ; "Bluechip Systems CoolEngine"],
        [218 ; EmNorc          ; EM_NORC             ; "EM_NORC"            ; "Nanoradio Optimized RISC"],
        [219 ; EmCsrKalimba    ; EM_CSR_KALIMBA      ; "EM_CSR_KALIMBA"     ; "CSR Kalimba architecture family"],
        [220 ; EmZ80           ; EM_Z80              ; "EM_Z80"             ; "Zilog Z80"],
        [221 ; EmVisium        ; EM_VISIUM           ; "EM_VISIUM"          ; "Controls and Data Services VISIUMcore processor"],
        [222 ; EmFt32          ; EM_FT32             ; "EM_FT32"            ; "FTDI Chip FT32 high performance 32-bit RISC architecture"],
        [223 ; EmMoxie         ; EM_MOXIE            ; "EM_MOXIE"           ; "Moxie processor family"],
        [224 ; EmAmdgpu        ; EM_AMDGPU           ; "EM_AMDGPU"          ; "AMD GPU architecture"],
        // reserved 225–242 Reserved for future use
        [243 ; EmRiscv         ; EM_RISCV            ; "EM_RISCV"           ; "RISC-V"],
        [244 ; EmLanai         ; EM_LANAI            ; "EM_LANAI"           ; "Lanai processor"],
        [245 ; EmCeva          ; EM_CEVA             ; "EM_CEVA"            ; "CEVA Processor Architecture Family"],
        [246 ; EmCevaX2        ; EM_CEVA_X2          ; "EM_CEVA_X2"         ; "CEVA X2 Processor Family"],
        [247 ; EmBpf           ; EM_BPF              ; "EM_BPF"             ; "Linux BPF – in-kernel virtual machine"],
        [248 ; EmGraphcoreIpu  ; EM_GRAPHCORE_IPU    ; "EM_GRAPHCORE_IPU"   ; "Graphcore Intelligent Processing Unit"],
        [249 ; EmImg1          ; EM_IMG1             ; "EM_IMG1"            ; "Imagination Technologies"],
        [250 ; EmNfp           ; EM_NFP              ; "EM_NFP"             ; "Netronome Flow Processor (NFP)"],
        [251 ; EmVe            ; EM_VE               ; "EM_VE"              ; "NEC Vector Engine"],
        [252 ; EmCsky          ; EM_CSKY             ; "EM_CSKY"            ; "C-SKY processor family"],
        [253 ; EmArcCompact364 ; EM_ARC_COMPACT3_64  ; "EM_ARC_COMPACT3_64" ; "Synopsys ARCv2.3 64-bit"],
        [254 ; EmMcs6502       ; EM_MCS6502          ; "EM_MCS6502"         ; "MOS Technology MCS 6502 processor"],
        [255 ; EmArcCompact3   ; EM_ARC_COMPACT3     ; "EM_ARC_COMPACT3"    ; "Synopsys ARCv2.3 32-bit"],
        [256 ; EmKvx           ; EM_KVX              ; "EM_KVX"             ; "Kalray VLIW core of the MPPA processor family"],
        [257 ; Em65816         ; EM_65816            ; "EM_65816"           ; "WDC 65816/65C816"],
        [258 ; EmLoongarch     ; EM_LOONGARCH        ; "EM_LOONGARCH"       ; "Loongson Loongarch"],
        [259 ; EmKf32          ; EM_KF32             ; "EM_KF32"            ; "ChipON KungFu32"],
        [260 ; EmU16U8Core     ; EM_U16_U8CORE       ; "EM_U16_U8CORE"      ; "LAPIS nX-U16/U8"],
        [261 ; EmTachyum       ; EM_TACHYUM          ; "EM_TACHYUM"         ; "Reserved for Tachyum processor"],
        [262 ; Em56800Ef       ; EM_56800EF          ; "EM_56800EF"         ; "NXP 56800EF Digital Signal Controller (DSC)"],
        [263 ; EmSbf           ; EM_SBF              ; "EM_SBF"             ; "Solana Bytecode Format"],
        [264 ; EmAiengine      ; EM_AIENGINE         ; "EM_AIENGINE"        ; "AMD/Xilinx AIEngine architecture"],
        [265 ; EmSimaMla       ; EM_SIMA_MLA         ; "EM_SIMA_MLA"        ; "SiMa MLA"],
        [266 ; EmBang          ; EM_BANG             ; "EM_BANG"            ; "Cambricon BANG"],
        [267 ; EmLoonggpu      ; EM_LOONGGPU         ; "EM_LOONGGPU"        ; "Loongson LoongGPU"],
        [268 ; EmSw64          ; EM_SW64             ; "EM_SW64"            ; "Wuxi Institute of Advanced Technology SW64"],
        [269 ; EmAiectrlcode   ; EM_AIECTRLCODE      ; "EM_AIECTRLCODE"     ; "AMD/Xilinx AIEngine ctrlcode"],
    ]
);
