//! gABI validation for dynamic-array relationships.

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ValidationError {
    MalformedDynamicArray,
    MissingNullTerminator,
    ReservedTag { index: usize, raw: i64 },
    MissingStringTable,
    MissingSymbolTable,
    MissingStringTableSize,
    MissingSymbolEntrySize,
    MissingHashOrSymbolTableSize,
    SymbolEntrySizeMismatch { expected: u64, actual: u64 },
    SymbolTableSizeNotEntryMultiple,
    ExecutableMissingRelocationTable,
    RelocationMissingSize,
    RelocationMissingEntrySize,
    RelocationEntrySizeMismatch { expected: u64, actual: u64 },
    RelocationSizeNotEntryMultiple,
    RelocationWithAddendMissingSize,
    RelocationWithAddendMissingEntrySize,
    RelocationWithAddendEntrySizeMismatch { expected: u64, actual: u64 },
    RelocationWithAddendSizeNotEntryMultiple,
    JumpRelocationMissingSize,
    JumpRelocationMissingFormat,
    JumpRelocationInvalidFormat { raw: u64 },
    JumpRelocationSizeNotEntryMultiple,
    DynamicRelocationTablesUnavailable,
    DynamicRelocationSymbolIndexOutOfBounds {
        table_index: usize,
        entry_index: usize,
        symbol_index: u32,
    },
    ReservedFlags { bits: u64 },
    DynamicStringTableUnavailable,
    DynamicStringTableInvalid(super::super::string_table::ValidationError),
    DynamicSymbolTableUnavailable,
    DynamicSymbolTableInvalid(super::super::dynamic_symbol_table::ValidationError),
    DynamicHashTableUnavailable,
    DynamicHashTableInvalid(super::super::hash::ValidationError),
    InvalidStringOffset {
        index: usize,
        tag: super::Tag,
        offset: u64,
    },
    InitializationArrayMissingSize,
    TerminationArrayMissingSize,
    PreInitializationArrayMissingSize,
    PreInitializationInSharedObject,
    InitializationArraySizeNotPointerMultiple,
    TerminationArraySizeNotPointerMultiple,
    PreInitializationArraySizeNotPointerMultiple,
    RelativeRelocationMissingSize,
    RelativeRelocationMissingEntrySize,
    RelativeRelocationEntrySizeMismatch,
    RelativeRelocationSizeNotEntryMultiple,
    RelativeRelocationTableUnavailable,
    RelativeRelocationFirstEntryMustBeAddress,
}
