#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Error {
    InvalidHeader,
    UnsupportedClass,
    UnsupportedEndianness,
    UnsupportedType,
    UnsupportedMachine,
    InvalidProgramHeaderTable,
    InvalidProgramHeader,
    UnsupportedInterpreter,
    UnsupportedDynamicLinking,
    UnsupportedTls,
    NoLoadableSegments,
    EntryOutsideExecutableSegment,
    StackConstructionFailed,
    MappingFailed,
    ProtectionFailed,
    FileReadFailed,
    FileOpenFailed,
    FileMetadataFailed,
    AddressOverflow,
    InvalidInterpreter,
    InterpreterUnavailable,
}
