ample::enum_flag!(
    u32;
    "Data endianness";
    pub enum Flag {
        [1; ZLIB; ELFCOMPRESS_ZLIB; "ELFCOMPRESS_ZLIB"; "ELFCOMPRESS_ZLIB"],
        [2; ZSTD; ELFCOMPRESS_ZSTD; "ELFCOMPRESS_ZSTD"; "ELFCOMPRESS_ZSTD"],
        [0x60000000; LOOS; ELFCOMPRESS_LOOS; "ELFCOMPRESS_LOOS"; "ELFCOMPRESS_LOOS"],
        [0x6fffffff; HIOS; ELFCOMPRESS_HIOS; "ELFCOMPRESS_HIOS"; "ELFCOMPRESS_HIOS"],
        [0x70000000; LOPROC; ELFCOMPRESS_LOPROC; "ELFCOMPRESS_LOPROC"; "ELFCOMPRESS_LOPROC"],
        [0x7fffffff; HIPROC; ELFCOMPRESS_HIPROC; "ELFCOMPRESS_HIPROC"; "ELFCOMPRESS_HIPROC"],
    }
);
